<template>
    <v-card
        v-if="calendarURL"
        class="mx-auto mt-8"
        variant="outlined"
    >
        <v-toolbar
            :flat="true"
            color="green"
            density="compact"
        >
            <v-toolbar-title>Your Generated Calendar</v-toolbar-title>
        </v-toolbar>

        <v-card-text>
            <p class="mb-3">The link for your generated calendar is: <b>{{ calendarURL }}</b></p>

            <p>To add the calendar to your Google Calendar account, follow these steps:</p>

            <ul class="ml-6 mb-4">
                <li>Go to Google Calendar</li>
                <li>On the left panel, go to 'Other Calendars</li>
                <li>Click on the '+'</li>
                <li>Click on 'From URL'</li>
                <li>Insert the URL generated by usicalendar</li>
                <li>Click on 'Add calendar'</li>
            </ul>

            <p>To add the calendar to your Apple Calendar account, follow these steps:</p>

            <ul class="ml-6 mb-4">
                <li>Open the calendar app on your Mac</li>
                <li>Go to 'File' > 'New Calendar Subscription'</li>
                <li>Insert the URL generated by usicalendar</li>
                <li>Click on 'OK'</li>
            </ul>
        </v-card-text>
    </v-card>
</template>

<script>
import {mapState} from "vuex";

export default {
    computed: {
        ...mapState(['calendarURL'])
    }
}
</script>
