name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Building project
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy script
        run: |
          git config user.name "EdoardoRiggio" && git config user.email "edo.riggio19@gmail.com"
          sh ./scripts/deploy.sh
